# Użycie obrazu bazowego z Pythonem
FROM python:3.9-slim

# Ustawienie katalogu roboczego
WORKDIR /app

# Skopiowanie lokalnego pliku Python do obrazu
COPY hello.py .

# Ustawienie komendy startowej
CMD ["python", "hello.py"]
